### ISSUE TITLE
Automatické pokračování

### ISSUE THREAD

**Issue by xpelanek** [amertak/Fractions#3]
... po správném řešení automaticky pokračovat (po malé prodlevě), tj. člověk nemusí klikat na "Další příklad" (nebo alespoň to klikání nějak usnadnit, teď člověk musí jezdit myší tam a zpět... nebo aspoň Enter).

Režim "automaticky pokračovat po správné odpovědi, po špatné vynutit explicitní potvrzení pokračování" používáme u několika dalších systémů.

**Comment by slaweet** [comment]
IMO umožnit pokračovat klávesou Enter je vhodné každopádně (i po špatné odpovědi)

**Comment by amertak** [comment]
Nelibi se mi predstava automatickeho pokracovani, obecne nemam rad pokud to nemam pod kontrolou.

Nasadil jsem verzi, kde enter jak teda odesle priklad, tak v pripade ukonceneho prikladu presune na dalsi.
