### ISSUE TITLE
Výsledek v základním tvaru

### ISSUE THREAD

**Issue by xpelanek** [amertak/Fractions#4]
Výsledek dělení očekává v základním tvaru, ale není to uvedeno v zadání.

**Comment by amertak** [comment]
Tam je to trochu jinak. Veme to vysledek i v nezakladnim tvaru, ale pokud clovek udela chybu, tak to zobrazi spravnou odpoved v zakkladnim tvaru.

**Comment by xpelanek** [comment]
Hm, tak to byl asi problém v tom, že neumím počítat. Teď jsem to zkoušel a je to opravdu nejspíš OK.
