### ISSUE TITLE
Admin statistiky

### ISSUE THREAD

**Issue by xpelanek** [amertak/Fractions#6]
Přehled nějakých základních informací o provozu (hodí se i pro odchytávání chyb a divného chování):
  * statistiky provozu "per day" - počet řešitelů, odpovědí, průměrná úspěšnost
  * statistiky "konceptů" - kolik odpovědí v každé kategorii, prům. úspěšnost
  * statistiky použití otázek (nejčastěji použité otázky)
  * statistiky obtížnosti otázek (nejlehčí, nejtěžší)

**Comment by amertak** [comment]
Nahodil jsem admin statistiky, Aby se zobrazily, tak se prosim odhlas a prihlas :)

**Comment by amertak** [comment]
Jsou ok tak jak je to ted?

**Comment by thran** [comment]
Pro začátek asi dobrý, ono se ukáže co bude potřeba. Bylo by možné udělat nějaký náhled těch jednotlivých otázek? Ty data jsou těžko čitelné, ale možná je to moc práce.

Vidí to všichni uživatelé? Pokud to tak je, tak bych to buď nějak omezil, nebo aspoň skryl (odkaz někde jinde než v panelu).

**Comment by amertak** [comment]
Ja tam mam zatim chybu ze to vidi vsichni co se lognou pres FB, budu muset vyresit.

Nahled otazek. To bude orisek, ale napada me leda zatim presmerovat primo na ten priklad. Takovy "sandbox"

**Comment by amertak** [comment]
Oboji vyreseno :)
