### ISSUE TITLE
Po zodpovězení zobrazit právnou odpověd i mojí špatnou.

### ISSUE THREAD

**Issue by slaweet** [amertak/Fractions#8]
Po mojí první špatné odpovědi se mi stalo, že jsem byl zmaten, protože tu červeně zbarvenou správnou odpověď jsem považoval za moji špatnou odpověď (nevím co jsem tam vlastně zadal). V příkladech na násobení zlomků.

**Comment by amertak** [comment]
Zatim bych to nemenil, nemam napad jak to udelat pekne a srozumitelne.

**Comment by slaweet** [comment]
Představoval bych si, že se špatná odpověď přeškrtne a obarví na červeno a vedle se zobrazí zeleně správná odpověď.

**Comment by amertak** [comment]
Casto bojuju s malo mistem, ale pokusim se to dat tam, kam se mi to vleze :)

**Comment by amertak** [comment]
Nahozeno.
