### ISSUE TITLE
Typ příkladu "vyber na ose" je matoucí

### ISSUE THREAD

**Issue by slaweet** [amertak/Fractions#9]
Hned první příklad: "vyber 2/9 na ose" mě celkem vyvedl z míry. Než jsem pochopil, že osa mezi 0 a 1 je rozdělena na devítiny a ne desetiny. Samozřejmě to zpětně dává smysl, ale chvíli jsem se na tom zasekl. Nevím co s tím, ale IMO to kazí user experience. Možná označit tu osu 0 a 9/9. Ten typ příkladu vyber na ose je nakonec zbytečně jednoduchý když mám osu rozdělenu na díly podle jmenovatele.

Ale jinak mi celá aplikace velice líbí, jak to vypadá a funguje :-).

**Comment by amertak** [comment]
Asi jsem presne nepochopil co je tam za problem :)

Jinak diky ;)

**Comment by xpelanek** [comment]
Mám stejný dojem, jako Víťa, to dělení na "devítiny" nebo jiné nestandardní části je A) matoucí, B) vede k triviálním úlohám (když se člověk zorientuje v nestandardním zobrazení). Asi bych výrazně upravil tento typ příkladu - dát tam normální osu s desetinami a dotaz typu "který z vyznačených tří bodů zobrazuje 2/9" (multiple choice otázka s výběrem ze 3 možností - 3 barevné body).

**Comment by amertak** [comment]
Upravim to, bude to sice trochu tezsi ale zato srozumitelnejsi.

**Comment by amertak** [comment]
Hotovo.
